// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeRARzttaeky-4hN9syUm06rLC0OsMqoM',
    appId: '1:1027541737617:web:932a7f5e452d288584df30',
    messagingSenderId: '1027541737617',
    projectId: 'gemini-5fa54',
    authDomain: 'gemini-5fa54.firebaseapp.com',
    storageBucket: 'gemini-5fa54.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfBkrAcGPYAW-It0Df2HRxrlahH2eBelE',
    appId: '1:1027541737617:android:830943e28cf4070084df30',
    messagingSenderId: '1027541737617',
    projectId: 'gemini-5fa54',
    storageBucket: 'gemini-5fa54.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeRARzttaeky-4hN9syUm06rLC0OsMqoM',
    appId: '1:1027541737617:web:f6682d67c13bd01b84df30',
    messagingSenderId: '1027541737617',
    projectId: 'gemini-5fa54',
    authDomain: 'gemini-5fa54.firebaseapp.com',
    storageBucket: 'gemini-5fa54.firebasestorage.app',
  );
}
