// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:gmail_enhancer_final/config/env.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: Env.firebaseWebApi,
    appId: Env.firebaseWebAppId,
    messagingSenderId: '1027541737617',
    projectId: 'gemini-5fa54',
    authDomain: 'gemini-5fa54.firebaseapp.com',
    storageBucket: 'gemini-5fa54.firebasestorage.app',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: Env.firebaseAndroidApi,
    appId: Env.firebaseAndroidAppId,
    messagingSenderId: '1027541737617',
    projectId: 'gemini-5fa54',
    storageBucket: 'gemini-5fa54.firebasestorage.app',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: Env.firebaseWindowsApi,
    appId: Env.firebaseWindowsAppId,
    messagingSenderId: '1027541737617',
    projectId: 'gemini-5fa54',
    authDomain: 'gemini-5fa54.firebaseapp.com',
    storageBucket: 'gemini-5fa54.firebasestorage.app',
  );
}
